include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_single_quotes
    - unawaited_futures
    - cancel_subscriptions
    - close_sinks
